### ISSUE TITLE
Cache Login credentials

### ISSUE THREAD

**Issue by BaroDevelopment** [dblanovschi/DiscordPanel#1]
I have to relogin everytime I restart IDEA. Is it possible to cache the session somehow?

**Comment by dnbln** [comment]
Hello! Yes it should be possible by tweaking the CefSettings. I actually tried to do this back in July but wasn't able to get anywhere, so I guess it's time to try again.

**Comment by BaroDevelopment** [comment]
> Hello! Yes it should be possible by tweaking the CefSettings. I actually tried to do this back in July but wasn't able to get anywhere, so I guess it's time to try again.

that would be really great! Because it is really annoying to login everytime. Especially if you have 2FA enabled ;)

**Comment by dnbln** [comment]
It's now possible, by saving the session on-disk in a non-temporary location. I just published version `0.1.3`; you can get it from github releases or from the jetbrains plugin marketplace(when the update gets approved). Then just go in `Settings > Other settings > Discord Panel` and select a folder where to store the CEF session data. Changes will apply the next time you open the tool window(might need restarting the IDE), and that will (probably) be the last time you will need to log in again.

Edit: 0.1.3 just got approved, and can be downloaded from the marketplace now.

**Comment by BaroDevelopment** [comment]
Your Plugin is not working on MacOs since this update and is working on Windows. How can I debug this plugin?

Maybe you add me in Discord and we talk there? 

My name is: Baͩrͤoͮ#3168

**Comment by dnbln** [comment]
> Maybe you add me in Discord and we talk there?
> My name is: Baͩrͤoͮ#3168

Ok just made a server for this plugin: https://discord.gg/6hNGxHXrph. Feel free to join it.
